### ISSUE TITLE
一些小的知识

### ISSUE THREAD

**Issue by dounai1306** [dounai1306/dounai1306.github.io#10]
em的默认值
当浏览器未经更改设置的情况下，em的默认值为16px

优雅降级和渐进增强
随着css3的快速发展，一些浏览器已经可以很好的支持一部分效果，但是对于低版本浏览器来讲，由于不支持css3，那么在高版本浏览器使用css3，在低版本浏览器中只需要保证基本规范既可。
优雅降级是高版本向低版本的一种兼容，渐进增强是低版本向高版本的兼容。

css盒模型
margin、border、padding、content

屏蔽ios和android下点击元素时出现的半透明灰色阴影
`-webkit-tap-highlight-color:rgba(255,255,255,0)`

字体抗锯齿
`-webkit-font-smoothing:antialiased`

移除IOS原生样式
```css
input[type=”button”], input[type=”submit”], input[type=”reset”] {
    -webkit-appearance: push-button;
    -webkit-appearance: none;
    white-space: pre;
}
```

手机点击出现蓝色框
`-webkit-tap-highlight-color:rgba(255,255,255,0);`

屏蔽阴影
`-webkit-appearance:none`

禁止选择文本
`-webkit-user-select:none`

Retina图片
```css
background-image: url(no-image-set.png);
background: image-set(url(foo-lowres.png) 1x,url(foo-highres.png) 2x) center;
```

开启GPU加速
`transform: translate3d;`

中英文混排
```html
<div style="width:300px;margin:0 auto;text-align:justify;letter-spacing:-0.02em;">
说好了要为幸福 一天天地练习 说好了要为幸福 一天天地练习 练习 Laugh a little more Love myself a little more 要学会更加善待我自己 为你我变成了 Better me
什么距离都不算是真的分离 想念和默契能代替一切言语 有一天生命会老去 还好谢谢有你 在你眼中 I see the better in me Coz I can Smile a little more Sing a little
more Feel a little more 全因为你
</div>
```
