### ISSUE TITLE
before & after 多边进度

### ISSUE THREAD

**Issue by dounai1306** [dounai1306/dounai1306.github.io#20]
<img src="https://raw.githubusercontent.com/dounai1306/other/master/img/before%26after.jpg">

```html
<div class="dounai">
	<div class="menu menu-1">menu1</div>
	<div class="menu menu-2">menu2</div>
	<div class="menu menu-3">menu3</div>
	<div class="menu menu-4">menu4</div>
</div>
```

```css
.dounai .menu {
	width:100px;
	height:30px;
	line-height:30px;
	display:inline-block;
	padding:0 20px;
	box-sizing:border-box;
	position:relative;
	color:#fff
}
.dounai .menu::before {
	box-sizing: border-box;
	position: absolute;
	content: "";
	border-top: 10px solid;
	border-bottom: 10px solid;
	border-bottom-color: inherit;
	border-left: 10px solid transparent;
	border-top-color: inherit;
	left: -10px;
	top: 0;
	height: 100%;
	width: 10px;
}
.dounai .menu::after {
	box-sizing: border-box;
	position: absolute;
	content: "";
	border-top: 10px solid transparent;
	border-bottom: 10px solid transparent;
	border-left: 10px solid;
	border-left-color: inherit;
	right: -10px;
	top: 0;
	height: 100%;
	width: 10px;
}
.menu-1 {
	background:#F1C40F;
	border-color:#F1C40F
}
.menu-2 {
	background:#F39C12;
	border-color:#F39C12
}
.menu-3 {
	background:#E67E22;
	border-color:#E67E22
}
.menu-4 {
	background:#D35400;
	border-color:#D35400
}
```
